### ISSUE TITLE
B: Session table exceeds quota.

### ISSUE THREAD

**Issue by xinbenlv** [google/wikiloop-battlefield#173]
`Session` table exceeds quota
Consider periodic purging.

```
Error: Error setting BT4tRfXLA3t005s2LpxLFhHclS21HqR2 to Session {
  cookie: {
    path: '/',
    _expires: 2020-05-09T21:33:53.083Z,
    originalMaxAge: 7776000000,
    httpOnly: true
  }
}: quota exceeded
    at /home/zzn_google/ws/wikiloop-battlefield/node_modules/connect-mongodb-session/index.js:226:21
    at /home/zzn_google/ws/wikiloop-battlefield/node_modules/connect-mongodb-session/node_modules/mongodb/lib/utils.js:411:14
    at /home/zzn_google/ws/wikiloop-battlefield/node_modules/connect-mongodb-session/node_modules/mongodb/lib/utils.js:397:27
    at ClientSession.endSession (/home/zzn_google/ws/wikiloop-battlefield/node_modules/mongodb-core/lib/sessions.js:134:41)
    at executeCallback (/home/zzn_google/ws/wikiloop-battlefield/node_modules/connect-mongodb-session/node_modules/mongodb/lib/utils.js:395:17)
    at updateCallback (/home/zzn_google/ws/wikiloop-battlefield/node_modules/connect-mongodb-session/node_modules/mongodb/lib/operations/collection_ops.js:1402:19)
    at /home/zzn_google/ws/wikiloop-battlefield/node_modules/connect-mongodb-session/node_modules/mongodb/lib/operations/collection_ops.js:1502:62
    at handleCallback (/home/zzn_google/ws/wikiloop-battlefield/node_modules/connect-mongodb-session/node_modules/mongodb/lib/utils.js:128:55)
    at /home/zzn_google/ws/wikiloop-battlefield/node_modules/connect-mongodb-session/node_modules/mongodb/lib/operations/collection_ops.js:1465:14
    at /home/zzn_google/ws/wikiloop-battlefield/node_modules/mongodb-core/lib/connection/pool.js:397:18
    at processTicksAndRejections (internal/process/task_queues.js:79:11)

```

**Comment by xinbenlv** [comment]
Temp fix by clearing session data. A long term solution will be a periodic-purge or an on-demand purging.

**Comment by xinbenlv** [comment]
We done adding an expiration index.
