### ISSUE TITLE
`npm run dev` crashes due to the score module

### ISSUE THREAD

**Issue by sohomdatta1** [google/wikiloop-battlefield#272]
Whenever I run `npm run dev` to run the server locally, the server crashes almost immediately with the following error

```
/home/sohom/mw-workspace/wikiloop-battlefield/node_modules/mysql2/lib/connection_config.js:74
    this.isServer = options.isServer;
                            ^
TypeError: Cannot read property 'isServer' of undefined
    at new ConnectionConfig (/home/sohom/mw-workspace/wikiloop-battlefield/node_modules/mysql2/lib/connection_config.js:74:29)
    at new PoolConfig (/home/sohom/mw-workspace/wikiloop-battlefield/node_modules/mysql2/lib/pool_config.js:10:29)
    at Object.exports.createPool (/home/sohom/mw-workspace/wikiloop-battlefield/node_modules/mysql2/index.js:20:29)
    at Object.<anonymous> (/home/sohom/mw-workspace/wikiloop-battlefield/server/routers/api/score.ts:24:20)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Module.m._compile (/home/sohom/mw-workspace/wikiloop-battlefield/node_modules/ts-node/src/index.ts:837:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Object.require.extensions.<computed> [as .ts] (/home/sohom/mw-workspace/wikiloop-battlefield/node_modules/ts-node/src/index.ts:840:12)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/sohom/mw-workspace/wikiloop-battlefield/server/routers/api/index.ts:18:1)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Module.m._compile (/home/sohom/mw-workspace/wikiloop-battlefield/node_modules/ts-node/src/index.ts:837:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Object.require.extensions.<computed> [as .ts] (/home/sohom/mw-workspace/wikiloop-battlefield/node_modules/ts-node/src/index.ts:840:12)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/sohom/mw-workspace/wikiloop-battlefield/server/index.ts:29:1)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Module.m._compile (/home/sohom/mw-workspace/wikiloop-battlefield/node_modules/ts-node/src/index.ts:837:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Object.require.extensions.<computed> [as .ts] (/home/sohom/mw-workspace/wikiloop-battlefield/node_modules/ts-node/src/index.ts:840:12)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
```
The error seems to be caused by [this line](https://github.com/google/wikiloop-battlefield/blob/master/server/routers/api/score.ts#L24) in `server/routers/api/score.ts` due to `process.env.STIKI_MYSQL` not being defined.

**Comment by xinbenlv** [comment]
Thank you for letting us know. I will address it shortly

**Comment by xinbenlv** [comment]
This shall be fixed, can you `git pull` and check, sohomdatta1@? Again thank you for reporting

**Comment by sohomdatta1** [comment]
Yup, the fix works :smile:
