### ISSUE TITLE
B: "request token not found" when doing passport authenticate steep

### ISSUE THREAD

**Issue by xinbenlv** [google/wikiloop-battlefield#69]
Related to #61 

Sometimes it will get: 
```
XXX req.session = {
  "cookie": {
    "originalMaxAge": null,
    "expires": null,
    "httpOnly": true,
    "path": "/"
  }
}
XXX self._key = oauth:mediawiki
Error: failed to find request token in session
    at Strategy.OAuthStrategy.authenticate (/Users/zzn/ws/wikiloop-battlefield/node_modules/passport-oauth/lib/passport-oauth/strategies/oauth.js:127:25)
    at attempt (/Users/zzn/ws/wikiloop-battlefield/node_modules/passport/lib/middleware/authenticate.js:361:16)
    at authenticate (/Users/zzn/ws/wikiloop-battlefield/node_modules/passport/lib/middleware/authenticate.js:362:7)
    at Layer.handle [as handle_request] (/Users/zzn/ws/wikiloop-battlefield/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/zzn/ws/wikiloop-battlefield/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/Users/zzn/ws/wikiloop-battlefield/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/zzn/ws/wikiloop-battlefield/node_modules/express/lib/router/layer.js:95:5)
    at /Users/zzn/ws/wikiloop-battlefield/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/Users/zzn/ws/wikiloop-battlefield/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/zzn/ws/wikiloop-battlefield/node_modules/express/lib/router/index.js:275:10)
    at SessionStrategy.strategy.pass (/Users/zzn/ws/wikiloop-battlefield/node_modules/passport/lib/middleware/authenticate.js:338:9)
    at SessionStrategy.authenticate (/Users/zzn/ws/wikiloop-battlefield/node_modules/passport/lib/strategies/session.js:75:10)
    at attempt (/Users/zzn/ws/wikiloop-battlefield/node_modules/passport/lib/middleware/authenticate.js:361:16)
    at authenticate (/Users/zzn/ws/wikiloop-battlefield/node_modules/passport/lib/middleware/authenticate.js:362:7)
    at Layer.handle [as handle_request] (/Users/zzn/ws/wikiloop-battlefield/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/zzn/ws/wikiloop-battlefield/node_modules/express/lib/router/index.js:317:13)
    at /Users/zzn/ws/wikiloop-battlefield/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/zzn/ws/wikiloop-battlefield/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/zzn/ws/wikiloop-battlefield/node_modules/express/lib/router/index.js:275:10)
    at initialize (/Users/zzn/ws/wikiloop-battlefield/node_modules/passport/lib/middleware/initialize.js:53:5)
    at Layer.handle [as handle_request] (/Users/zzn/ws/wikiloop-battlefield/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/zzn/ws/wikiloop-battlefield/node_modules/express/lib/router/index.js:317:13)
    at /Users/zzn/ws/wikiloop-battlefield/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/zzn/ws/wikiloop-battlefield/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/zzn/ws/wikiloop-battlefield/node_modules/express/lib/router/index.js:275:10)
    at Immediate.<anonymous> (/Users/zzn/ws/wikiloop-battlefield/node_modules/express-session/index.js:495:7)
    at runCallback (timers.js:706:11)
    at tryOnImmediate (timers.js:676:5)
```

**Comment by xinbenlv** [comment]
This comes up every once awhile, but I cannot stably reproduce it.

**Comment by epicfaace** [comment]
Try looking at https://github.com/jaredhanson/passport-twitter/issues/45 or https://stackoverflow.com/questions/11075629/passport-twitter-failed-to-find-request-token-in-session

**Comment by xinbenlv** [comment]
It turns out when there is a failure of this bug, the requestToken is actually set

```
wpEditToken: <redacted>
title: Special:OAuth/authorize
wpaction: accept
wpconfirmUpdate: 1
consumerKey: <redacted>
requestToken: <redacted>
```

So I think there is something wrong within the `passport-mediawiki-oauth`
![image](https://user-images.githubusercontent.com/640325/66617145-bb2ed900-eb88-11e9-8d71-4800b3346120.png)

**Comment by xinbenlv** [comment]
I can now reliably reproduce the bug
1. open a new chrome tab and load `http://localhost:3000/?enableLogin=true` in chrome `tab 1`
2. use the chrome inspect tool to clear storage "Clear Site Data" of `tab 1`
3. open a second new chrome tab and load `https://meta.wikimedia.org/wiki/Special:OAuth` in chrome `tab 2`
4. use the chrome inspect tool to clear storage "Clear Site Data" of `tab 2`
5. click on the "Login" on `tab 1` and login through Oauth 1. At this step, the Oauth login will reliably ***succeed***.
6. Now without any clean up, directly open a new chrome tab and load `http://localhost:3000/?enableLogin=true` in chrome `tab 3`, click on login and try to login, it will reliably ***fail*** with `failed to find request token in session`.

**Comment by xinbenlv** [comment]
Reliably detected that session was not stored consistently. For example
```
[2019-10-14T23:47:27.594] [INFO] perf -  log request SESSION SESSION XXXX session for GET /auth/mediawiki/login { session_id: 'YOw8t5PRt8PFjK36NTSeJI2yYywlIi4i',
  session:
   Session {
     cookie:
      { path: '/',
        _expires: null,
        originalMaxAge: null,
        httpOnly: true },
     passport: { user: [Object] },
     'oauth:mediawiki':
      { oauth_token: '<redacted>',
        oauth_token_secret: '<redacted>' } } }
```
and 
```
[2019-10-14T23:47:31.362] [INFO] perf -  log request SESSION SESSION XXXX session for GET /api/stats { session_id: 'YOw8t5PRt8PFjK36NTSeJI2yYywlIi4i',
  session:
   Session {
     cookie:
      { path: '/',
        _expires: null,
        originalMaxAge: null,
        httpOnly: true },
     passport: { user: [Object] } } }
```

Probably related to:
https://github.com/expressjs/session/issues/464
