### ISSUE TITLE
The history (`marked`) is failing loading the number

### ISSUE THREAD

**Issue by xinbenlv** [google/wikiloop-battlefield#92]
The history (`marked`) is failing loading the number of total revisions like `index`. and here is a console exception, probalby related 
```
DOMException: Failed to execute 'appendChild' on 'Node': This node type does not support this method.
    at Object.appendChild (http://battlefield.wikiloop.org/_nuxt/c91a34d085f822ca58e2.js:2:41967)
    at m (http://battlefield.wikiloop.org/_nuxt/c91a34d085f822ca58e2.js:2:54732)
    at v (http://battlefield.wikiloop.org/_nuxt/c91a34d085f822ca58e2.js:2:54363)
    at _ (http://battlefield.wikiloop.org/_nuxt/c91a34d085f822ca58e2.js:2:54815)
    at I (http://battlefield.wikiloop.org/_nuxt/c91a34d085f822ca58e2.js:2:58205)
    at I (http://battlefield.wikiloop.org/_nuxt/c91a34d085f822ca58e2.js:2:58140)
    at I (http://battlefield.wikiloop.org/_nuxt/c91a34d085f822ca58e2.js:2:58140)
    at f.__patch__ (http://battlefield.wikiloop.org/_nuxt/c91a34d085f822ca58e2.js:2:58575)
    at f.t._update (http://battlefield.wikiloop.org/_nuxt/c91a34d085f822ca58e2.js:2:35632)
    at f.r (http://battlefield.wikiloop.org/_nuxt/c91a34d085f822ca58e2.js:2:65957)
```

**Comment by xinbenlv** [comment]
This is subsequently fixed by #98
